apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: jitsi-meet
data:
  # Jitsi Meet configuration
  JICOFO_AUTH_PASSWORD: "jicofoS3cureP@ss2025"
  JICOFO_COMPONENT_SECRET: "s3cr37"
  JICOFO_BRIDGE_MUC: "jvbbrewery@internal.auth.jitsi"
  JICOFO_BRIDGE_PASSWORD: "passw0rd"
  
  # JVB configuration
  JVB_AUTH_PASSWORD: "jvbS3cureP@ss2025"
  JVB_BREWERY_MUC: "jvbbrewery@internal.auth.jitsi"
  JVB_ENABLE_STATISTICS: "true"
  JVB_STATISTICS_TRANSPORT: "http"
  JVB_STATISTICS_PORT: "8080"
  
  # Prosody configuration
  PROSODY_AUTH_PASSWORD: "passw0rd"
  PROSODY_COMPONENT_SECRET: "s3cr37"
  PROSODY_BRIDGE_PASSWORD: "passw0rd"
  
  # Web configuration
  WEB_DOMAIN: "127.0.0.1"
  WEB_MEETING_DOMAIN: "127.0.0.1"
  JITSI_SERVER_URL: "127.0.0.1"
  JITSI_APP_BASE_URL: "127.0.0.1"
  ENABLE_LETSENCRYPT: "0"
  HTTP_PORT: "80"
  ENABLE_HTTP_REDIRECT: "0"
  ENABLE_TRANSCRIPTION: "0"
#  HTTPS_PORT: "8443"
  PUBLIC_URL: "https://meet.localhost"
  TZ: "Asia/Karachi"
  ENABLE_AUTH: "0"
  AUTH_TYPE: "jwt"
  JWT_APP_ID: "meet"
  JWT_APP_SECRET: "L3vSrziDXyhOxp2an5dNTRCYbfAEHWsU"
  ENABLE_GUESTS: "1"
  XMPP_DOMAIN: "127.0.0.1"
  XMPP_AUTH_DOMAIN: "auth.127.0.0.1"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.127.0.0.1"
  XMPP_MUC_DOMAIN: "muc.127.0.0.1"
  ENABLE_XMPP_WEBSOCKET: "1"
  XMPP_WEBSOCKET_URL: "wss://meet.localhost/xmpp-websocket"
  ENABLE_SUBDOMAINS: "false"
  JICOFO_AUTH_USER: "focus"
  JVB_AUTH_USER: "jvb"
  JVB_TCP_HARVESTER_PORT: "4443"
  JVB_TCP_MAPPED_PORT: "4443"
  JVB_STUN_SERVERS: "stun.l.google.com:19302"
  DOCKER_HOST_ADDRESS: "127.0.0.1"
  JVB_ADVERTISE_IPS: "127.0.0.1"
  JVB_PORT: "10000"
  JVB_TCP_PORT: "4443"
  JVB_COLIBRI_PORT: "8080"
  ENABLE_SINGLE_PORT: "true"
  JVB_SINGLE_PORT: "10000"
  JICOFO_COMPONENT_SECRET: "secretcomponent"
  ENABLE_STATISTICS: "1"
  JVB_ENABLE_COLIBRI_WEBSOCKET: "true"
  JVB_ENABLE_PROMETHEUS: "true"
  ENABLE_JIGASI: "0"
  ENABLE_JIBRI: "0"
  
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "jitsi_appointments"
  DB_USER: "postgres"
  
  # Prometheus configuration
  PROMETHEUS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  
  # Grafana configuration
  GRAFANA_ADMIN_PASSWORD: "admin"
  GRAFANA_PORT: "3000"
