apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jitsi-meet

resources:
  - namespace.yaml
  - storage.yaml
  - secrets.yaml
  - configmaps.yaml
  - postgres-deployment.yaml
  - prosody-deployment.yaml
  - jicofo-deployment.yaml
  - jvb-deployment.yaml
  - jitsi-api-deployment.yaml
  - web-deployment.yaml
  - monitoring.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: jitsi-meet
  app.kubernetes.io/instance: production
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: videoconferencing

images:
  - name: jitsiappointmentapi
    newTag: latest
  - name: jitsi/jvb
    newTag: stable-8922
  - name: jitsi/web
    newTag: stable-8922
  - name: jitsi/prosody
    newTag: stable-8922
  - name: jitsi/jicofo
    newTag: stable-8922
  - name: postgres
    newTag: "15"
  - name: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newTag: latest
  - name: otel/opentelemetry-collector
    newTag: latest 