apiVersion: v1
kind: Namespace
metadata:
  name: jitsi-meet
  labels:
    name: jitsi-meet
    app: jitsi-meet
    environment: production
  annotations:
    description: "Jitsi Meet autoscaling namespace" 