apiVersion: v1
kind: Service
metadata:
  name: jitsi-appointment-api
spec:
  selector:
    app: jitsi-appointment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
