apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-appointment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-appointment-api
  template:
    metadata:
      labels:
        app: jitsi-appointment-api
    spec:
      containers:
        - name: api
          image: bilaltahirinvozone/jitsi-appointment-api:latest # Replace with your built image/tag
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          # Add other environment variables as needed
