global:
  publicURL: "https://meet.localhost"

ingress:
  enabled: true
  className: "nginx"
  ingressClassName: nginx
  hosts:
    - host: meet.localhost
      paths:
        - /
  tls:
    - hosts:
        - meet.localhost
      secretName: jitsi-localhost-tls

web:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: meet.localhost
        paths:
          - /
    tls:
      - hosts:
          - meet.localhost
        secretName: jitsi-localhost-tls

jicofo:
  enabled: true
  extraEnv:
    - name: JICOFO_AUTH_USER
      value: "focus"
    - name: JICOFO_AUTH_PASSWORD
      value: "StrongJicofoPassword123!"
    - name: JICOFO_COMPONENT_SECRET
      value: "secret"

prosody:
  enabled: true
  extraEnv:
    - name: XMPP_DOMAIN
      value: "meet.localhost"
    - name: XMPP_AUTH_DOMAIN
      value: "auth.meet.localhost"
    - name: JVB_AUTH_USER
      value: "jvb"
    - name: JVB_AUTH_PASSWORD
      value: "StrongJvbPassword123!"
    - name: JICOFO_AUTH_USER
      value: "focus"
    - name: JICOFO_AUTH_PASSWORD
      value: "StrongJicofoPassword123!"

jvb:
  enabled: true
  useNodeIP: true
  # publicIPs:
    #- "meet.localhost"  # Replace with your external IP if needed
  service:
    type: LoadBalancer
  extraEnv:
    - name: JVB_AUTH_USER
      value: "jvb"
    - name: JVB_AUTH_PASSWORD
      value: "StrongJvbPassword123!"
